const refs = {
    authorizationSection: document.querySelector('.authorization'),
    authorizationBoxWrap: document.querySelector('.authorization-box__wrap'),
    authorizationBoxRegisterWrap: document.querySelector('.authorization-box__register-wrap'),
    uniswapMessageTextWrap: document.querySelector('.error-auth'),
    authorizationLogInForm: document.querySelector('.authorization-box__form'),
    authorizationLogInEmailInput: document.getElementById('login-email'),
    authorizationLogInPasswordInput: document.getElementById('login-password'),
    authorizationButton: document.querySelector('.authorization-box__btn'),
    authorizationTextPink: document.querySelector('.authorization-box__text_pink'),
    authorizationRegisterTextPink: document.querySelector('.authorization-box__register-text_pink'),
    uniswapMarketExmark: document.querySelector('.uniswap-market__exmark'),
    uniswapMarketInfoWrap: document.querySelector('.uniswap-market__info-wrap'),
    linkToMarket: document.querySelector('.link-market'),
    linkToStake: document.querySelector('.link-stake'),
    linkToMyPositions: document.querySelector('.link-my-positions'),
    marketTokensGrid: document.querySelector('.market__tokens-grid'),
    marketTokensGridMob: document.querySelector('.market__tokens-grid-mob'),
    marketStakeForm: document.querySelector('.market__stake-form'),
    stakeFormSelectPair: document.getElementById('select-pair'),
    stakeFormPairWrap: document.querySelector('.stake-form__pair-wrap'),
    stakeFormLockPeriod: document.getElementById('market-lock-period'),
    stakeFormLpWrap: document.querySelector('.stake-form__lp-wrap'),
    marketMyPositions: document.querySelector('.market__my-positions'),
    navUserIcon: document.querySelector('.nav-user-icon-wrap'),
    headerSection: document.querySelector('.header'),
    headerMobSection: document.querySelector('.header-mob'),
    marketSection: document.querySelector('.market'),
    userProfileSection: document.querySelector('.user-profile'),
    referralProgramSection: document.querySelector('.referral-program'),
    dashboardSection: document.querySelector('.dashboard'),
    roadmapSection: document.querySelector('.roadmap'),
    footerSection: document.querySelector('.footer'),
    dashboard: document.querySelector('.nav-site-list__link-dashboard'),
    whitePaper: document.querySelector('.nav-site-list__link-white-paper'),
    roadmap: document.querySelector('.nav-site-list__link-roadmap'),
    deposit: document.querySelector('.nav-sum-list__link-deposit'),
    withdraw: document.querySelector('.nav-sum-list__link-withdraw'),
};

export const {
    authorizationSection,
    authorizationBoxWrap,
    authorizationBoxRegisterWrap,
    uniswapMessageTextWrap,
    authorizationLogInForm,
    authorizationLogInEmailInput,
    authorizationLogInPasswordInput,
    authorizationButton,
    authorizationTextPink,
    authorizationRegisterTextPink,
    uniswapMarketExmark,
    uniswapMarketInfoWrap,
    linkToMarket,
    linkToStake,
    linkToMyPositions,
    marketTokensGrid,
    marketTokensGridMob,
    marketStakeForm,
    stakeFormSelectPair,
    stakeFormPairWrap,
    stakeFormLockPeriod,
    stakeFormLpWrap,
    marketMyPositions,
    navUserIcon,
    headerSection,
    headerMobSection,
    marketSection,
    userProfileSection,
    referralProgramSection,
    dashboardSection,
    roadmapSection,
    footerSection,
    dashboard,
    whitePaper,
    roadmap,
    deposit,
    withdraw,
} = refs;