const refs = {
    authorizationBoxWrap: document.querySelector('.authorization-box__wrap'),
    authorizationBoxRegisterWrap: document.querySelector('.authorization-box__register-wrap'),
    uniswapMessageTextWrap: document.querySelector('.uniswap-message_text-wrap'),
    authorizationLogInForm: document.querySelector('.authorization-box__form'),
    authorizationLogInEmailInput: document.getElementById('login-email'),
    authorizationLogInPasswordInput: document.getElementById('login-password'),
    authorizationButton: document.querySelector('.authorization-box__btn'),
    authorizationTextPink: document.querySelector('.authorization-box__text_pink'),
    authorizationRegisterTextPink: document.querySelector('.authorization-box__register-text_pink'),
    uniswapMarketExmark: document.querySelector('.uniswap-market__exmark'),
    uniswapMarketInfoWrap: document.querySelector('.uniswap-market__info-wrap'),
    marketTokensList: document.querySelector('.market__tokens-list'),
    marketTokensListMob: document.querySelector('.market__tokens-list-mob'),
    marketTokensGrid: document.querySelector('.market__tokens-grid'),
    marketTokensGridMob: document.querySelector('.market__tokens-grid-mob'),
};

export const {
    authorizationBoxWrap,
    authorizationBoxRegisterWrap,
    uniswapMessageTextWrap,
    authorizationLogInForm,
    authorizationLogInEmailInput,
    authorizationLogInPasswordInput,
    authorizationButton,
    authorizationTextPink,
    authorizationRegisterTextPink,
    uniswapMarketExmark,
    uniswapMarketInfoWrap,
    marketTokensList,
    marketTokensListMob,
    marketTokensGrid,
    marketTokensGridMob,
} = refs;