const refs = {
    authorizationSection: document.querySelector('.authorization'),
    authorizationBoxWrap: document.querySelector('.authorization-box__wrap'),
    authorizationBoxRegisterWrap: document.querySelector('.authorization-box__register-wrap'),
    authorizationLogInForm: document.querySelector('.authorization-box__form'),
    authorizationLogInEmailInput: document.getElementById('login-email'),
    authorizationLogInPasswordInput: document.getElementById('login-password'),
    authorizationButton: document.querySelector('.authorization-box__btn'),
    authorizationTextPink: document.querySelector('.authorization-box__text_pink'),
    authorizationRegisterTextPink: document.querySelector('.authorization-box__register-text_pink'),
    
    uniswapMessageTextWrap: document.querySelector('.error-auth'),
    uniswapMarketBtnCreateStake: document.querySelector('.uniswap-dashboard__btn-create-stake'),
    uniswapMarketExmark: document.querySelector('.uniswap-dashboard__exmark'),
    uniswapMarketInfoWrap: document.querySelector('.uniswap-dashboard__info-wrap'),
    uniswapBackdropHeader: document.querySelector('.uniswap-backdrop-header'),
    uniswapMessageLogout: document.querySelector('.uniswap-message-logout'),
    uniswapMessageBtnLogout: document.querySelector('.uniswap-message-btn-logout'),
    uniswapMessageBtnNoLogout: document.querySelector('.uniswap-message-btn-logout-pink'),
    uniswapBackdropWarning: document.querySelector('.uniswap-backdrop-warning'),
    uniswapMessageWarning: document.querySelector('.uniswap-message-warning'),
    uniswapMessageBtnWarning: document.querySelector('.uniswap-message-btn-warning'),
    uniswapBackdropErrorValidate: document.querySelector('.uniswap-backdrop-error-validate'),
    uniswapMessageErrorValidate: document.querySelector('.uniswap-message-error-validate'),
    uniswapMessageBtnErrorValidate: document.querySelector('.uniswap-message-btn-error-validate'),
    uniswapBackdropErrorCreate: document.querySelector('.uniswap-backdrop-error-create'),
    uniswapMessageErrorCreate: document.querySelector('.uniswap-message-error-create'),
    uniswapMessageBtnErrorCreate: document.querySelector('.uniswap-message-btn-error-create'),
    uniswapBackdropSuccess: document.querySelector('.uniswap-backdrop-success'),
    uniswapMessageSuccess: document.querySelector('.uniswap-message-success'),
    uniswapMessageBtnSuccess: document.querySelector('.uniswap-message-btn-success'),
    
    linkToMarket: document.querySelector('.link-to-market'),
    linkToStake: document.querySelector('.link-to-stake'),
    linkToMyPositions: document.querySelector('.link-to-my-positions'),
    whitePaperMobLink: document.getElementById('white-paper-mob-link'),
    stakeMobLink: document.getElementById('stake-mob-link'),
    myPositionsMobLink: document.getElementById('my-positions-mob-link'),

    dashboardLink: document.querySelector('.nav__list-dashboard-link'),
    whitePaperLink: document.querySelector('.nav__list-white-paper-link'),
    roadmapLink: document.querySelector('.nav__list-roadmap-link'),
    faqLink: document.querySelector('.nav__list-faq-link'),
    myProfileLink: document.getElementById('my-profile-link'),
    referralProgramLink: document.getElementById('referral-program-link'),
    supportLink: document.getElementById('support-link'),
    logoutLink: document.getElementById('logout-link'),
    navUserIcon: document.querySelector('.nav__user-icon'),
    navUserSections: document.querySelector('.nav__user-sections'),

    headerSection: document.querySelector('.header'),
    footerSection: document.querySelector('.footer'),
    whitePaperSection: document.querySelector('.white-paper'),
    roadmapSection: document.querySelector('.roadmap'),
    userProfileSection: document.querySelector('.user-profile'),
    referralProgramSection: document.querySelector('.referral-program'),

    dashboardSection: document.querySelector('.dashboard'),
    TokensListItemWarning: document.querySelectorAll('.tokens-list__item-warning'),
    TokensListItemMobWarning: document.querySelectorAll('.tokens-list__item-mob-warning'),
    dashboardTokensGrid: document.querySelector('.dashboard__tokens-grid'),
    dashboardStakeForm: document.querySelector('.dashboard__stake-form'),
    stakeFormSelectPair: document.getElementById('stake-form-select-pair'),
    stakeFormPairWrap: document.querySelector('.stake-form__pair-wrap'),
    stakeFormPairText: document.querySelectorAll('.stake-form__pair-text'),
    stakeFormAmount: document.querySelector('.stake-form__input'),
    stakeFormLockPeriod: document.getElementById('stake-form-lock-period'),
    stakeFormLockPeriodWrap: document.querySelector('.stake-form__lock-period-wrap'),
    stakeFormLockPeriodText: document.querySelectorAll('.stake-form__lock-period-text'),
    dashboardMyPositions: document.querySelector('.dashboard__my-positions'),

    headerMobMenu: document.querySelector('.header__mob-menu'),
    mobMenuBackdrop: document.querySelector('.mob-menu__backdrop'),
    mobMenu: document.querySelector('.mob-menu'),

    supportSection: document.querySelector('.support'),
    supportBtn: document.querySelector('.support__btn'),
    createTicketCloseBtn: document.querySelector('.create-ticket__cross'),
    createTicketBackdrop: document.querySelector('.create-ticket__backdrop'),
    createTicket: document.querySelector('.create-ticket'),
    ticketSection: document.querySelector('.ticket'),
    ticketItem: document.querySelector('.ticket-list__item'),
    ticketArrow: document.querySelector('.ticket__arrow'),
    faqSection: document.querySelector('.faq'),
    faqItem: document.querySelector('.faq__item'),
    faqArrow: document.querySelector('.faq__item-arrow'),
};

export const {
    authorizationSection,
    authorizationBoxWrap,
    authorizationBoxRegisterWrap,
    authorizationLogInForm,
    authorizationLogInEmailInput,
    authorizationLogInPasswordInput,
    authorizationButton,
    authorizationTextPink,
    authorizationRegisterTextPink,
    
    uniswapMessageTextWrap,
    uniswapMarketBtnCreateStake,
    uniswapMarketExmark,
    uniswapMarketInfoWrap,
    uniswapBackdropHeader,
    uniswapMessageLogout,
    uniswapMessageBtnLogout,
    uniswapMessageBtnNoLogout,
    uniswapBackdropWarning,
    uniswapMessageWarning,
    uniswapMessageBtnWarning,
    uniswapBackdropErrorValidate,
    uniswapMessageErrorValidate,
    uniswapMessageBtnErrorValidate,
    uniswapBackdropErrorCreate,
    uniswapMessageErrorCreate,
    uniswapMessageBtnErrorCreate,
    uniswapBackdropSuccess,
    uniswapMessageSuccess,
    uniswapMessageBtnSuccess,

    linkToMarket,
    linkToStake,
    linkToMyPositions,
    whitePaperMobLink,
    stakeMobLink,
    myPositionsMobLink,
    
    dashboardLink,
    whitePaperLink,
    roadmapLink,
    faqLink,
    myProfileLink,
    referralProgramLink,
    supportLink,
    logoutLink,
    navUserIcon,
    navUserSections,

    headerSection,
    footerSection,
    whitePaperSection,
    roadmapSection,
    userProfileSection,
    referralProgramSection,

    dashboardSection,
    TokensListItemWarning,
    TokensListItemMobWarning,
    dashboardTokensGrid,
    dashboardStakeForm,
    stakeFormSelectPair,
    stakeFormPairWrap,
    stakeFormPairText,
    stakeFormAmount,
    stakeFormLockPeriod,
    stakeFormLockPeriodWrap,
    stakeFormLockPeriodText,
    dashboardMyPositions,

    headerMobMenu,
    mobMenuBackdrop,
    mobMenu,

    supportSection,
    supportBtn,
    createTicketCloseBtn,
    createTicketBackdrop,
    createTicket,
    ticketSection,
    ticketItem,
    ticketArrow,
    faqSection,
    faqItem,
    faqArrow,
} = refs;